apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: magento-nginx
spec:
  replicas: {{ .Values.nginx.replicas | default 1 }}
  selector:
    matchLabels:
      app: magento-nginx
  template:
    metadata:
      labels:
        app: magento-nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.nginx.port }}
              protocol: TCP
