apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-db
  namespace: {{ .Values.namespace }}
  labels:
    app: magento-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento-db
  template:
    metadata:
      labels:
        app: magento-db
    spec:
      containers:
        - name: magento-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.db.env.MYSQL_ROOT_PASSWORD }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.db.env.MYSQL_DATABASE }}"
            - name: MYSQL_USER
              value: "{{ .Values.db.env.MYSQL_USER }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.db.env.MYSQL_PASSWORD }}"
            # Disable SSL completely in MySQL server
            - name: MYSQL_SSL_MODE
              value: "DISABLED"
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
            - name: mysql-custom-config
              mountPath: /etc/mysql/conf.d/mysql-custom.cnf
              subPath: mysql-custom.cnf
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: magento-db-pvc
        - name: mysql-custom-config
          configMap:
            name: mysql-custom-config
      restartPolicy: Always
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-db-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.db.storage.size }}"
