apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-php
  namespace: {{ .Values.namespace }}
  labels:
    app: magento-php
spec:
  replicas: {{ .Values.php.replicas | default 1 }}
  selector:
    matchLabels:
      app: magento-php
  template:
    metadata:
      labels:
        app: magento-php
    spec:
      containers:
        - name: php
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
          ports:
            - containerPort: {{ .Values.php.port }}
          volumeMounts:
            - name: magento-shared
              mountPath: /var/www/html
      volumes:
        - name: magento-shared
          persistentVolumeClaim:
            claimName: magento-shared-pvc
