apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-shared-pvc
  namespace: magento2
spec:
  accessModes:
    - ReadWriteOnce  # <-- change from ReadWriteMany to ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: microk8s-hostpath
