apiVersion: v1
kind: Service
metadata:
  name: magento-db
  namespace: magento2
spec:
  selector:
    app: magento-db
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
