apiVersion: v1
kind: Service
metadata:
  name: magento-php
  namespace: magento2
spec:
  selector:
    app: magento-php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
